name: CI/CD Pipeline

on:
  push:
    branches:
      - action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code test!
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.USER }}/twm:latest .
          docker push ${{ secrets.USER }}/twm:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_GITHUB }}
          username: ${{ secrets.EC2_USER_GITHUB }}
          key: ${{ secrets.FOR_3_114_11_4_EC2 }}
          script: |
            sudo systemctl stop twm-docker
            docker rmi ${{ secrets.USER }}/twm:latest || true
            docker pull ${{ secrets.USER }}/twm:latest
            sudo systemctl start twm-docker
